# Generated by Django 5.1 on 2024-08-13 00:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('legenda', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('NEBULOSA', 'Nebulosa'), ('GALÁXIA', 'Galáxia'), ('PLANETA', 'Planeta'), ('ESTRELA', 'Estrela'), ('OUTRO', 'Outro')], default='', max_length=30)),
                ('descricao', models.TextField()),
                ('caminho_imagem', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/')),
                ('publicada', models.BooleanField(default=False)),
                ('data_imagem', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
