# Generated by Django 5.1 on 2024-08-15 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_imagem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='publicada',
            field=models.BooleanField(default=True),
        ),
    ]
