# Generated by Django 5.1 on 2024-08-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_alter_imagem_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='favoritada',
            field=models.BooleanField(default=False),
        ),
    ]
