# Generated by Django 5.1 on 2024-08-17 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_alter_like_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagem',
            old_name='num_likes',
            new_name='likes',
        ),
    ]
