# Generated by Django 5.1 on 2024-08-17 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0007_rename_num_likes_imagem_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='image',
            new_name='imagem',
        ),
        migrations.RemoveField(
            model_name='imagem',
            name='favoritada',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'imagem')},
        ),
        migrations.CreateModel(
            name='Favoritas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favoritada', models.BooleanField(default=False)),
                ('favoritada_at', models.DateTimeField(auto_now_add=True)),
                ('imagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favoritas', to='galeria.imagem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favoritas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'imagem')},
            },
        ),
    ]
